version: '3'

services:
  # rabbitmq:
  #   image: rabbitmq:3.12-management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d